services:
    # Application
    shot_app:
        container_name: shot_app
        build:
          args:
            user: siberfx
            uid: 1000
          context: .
          dockerfile: ./docker/app.dockerfile
        working_dir: /var/www
        restart: unless-stopped
        volumes:
            - ./:/var/www
        ports:
          # With SSL
            - "443:8443"
          # With HTTP
          #- "80:8443"
        depends_on:
            - shot_db
    # Web Server
    shot_web:
        container_name: shot_web
        environment:
          XDEBUG_IDE_KEY: "PHPSTORM"
          XDEBUG_REMOTE_HOST: "192.167.220.1"
          PHP_IDE_CONFIG: "serverName=Docker"
          DB_PORT: ${DB_PORT}
          DB_DATABASE: ${DB_DATABASE}
          DB_USERNAME: ${DB_USERNAME}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_HOST: ${DB_HOST}
        depends_on:
          - shot_db
          - shot_app
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8001:80
    # Database
    shot_db:
      image: mysql:8.0
      container_name: shot_db
      volumes:
          - dbdata:/var/lib/mysql
          - ./docker/sql-backup:/docker-entrypoint-initdb.d
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
          MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_USERNAME}
      ports:
          - "3306:3306"
      restart: unless-stopped
    # MongoDB
    mongodb:
        container_name: mongodb
        image: mongo
        ports:
            - 27017:27017
        logging:
            driver: none

    # Database management phpmyadmin
    shot_pma:
        image: phpmyadmin:latest
        container_name: shot_pma
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
            - PMA_PORT=${DB_PORT}
            - UPLOAD_LIMIT=300M
        depends_on:
            - shot_db
        ports:
            - 8080:80
    # Mailing Server
    shot_mailhog:
        container_name: shot_mailhog
        image: mailhog/mailhog
        logging:
            driver: 'none'
        ports:
            - 1025:1025
            - 8025:8025
    # Redis
    shot_redis:
        container_name: shot_redis
        image: redis:latest
        logging:
            driver: 'none'
        ports:
            - 6379:6379
volumes:
    dbdata:
